### PR TITLE
API: Fixes #69. Customisation of has|many_xxx relations

### LINKED ISSUE #69: Allow additional config driven fields in JSONDataFormatter
In `JSONDataFormatter` line 119 and 151 a baked-in set of three fields are returned for each object in a has_xxx relation which doesn't allow for much in the way of customisation, viz:

```
                $serobj->$relName = ArrayData::array_to_object(array(
                    "className" => $relClass,
                    "href" => "$href.json",
                    "id" => $obj->$fieldName
                ));
```

We should allow developers to specify additional fields to return here, declared in YML config viz:

```
                $serobj->$relName = ArrayData::array_to_object(array_replace([
                    "className" => $relClass,
                    "href" => "$href.json",
                    "id" => $obj->$fieldName
                ], $obj->config()->get('api_fields'));
```

Note the use of `array_replace()` so that userland config can also _override_ the defaults, not simply append to them.

### PR DESCRIPTION
**Pull request by phptek**

### CODE REVIEW

**Comment by phptek** [comment]
Failures look like composer dependency problems.

**Comment by robbieaverill** [comment]
Yeah the SilverStripe 4.0-4.2 branches have been deleted. I'll update Travis now in a separate commit/

**Review by robbieaverill — COMMENTED** [review]
Cool! The changes look good to me, but they probably need some unit tests. Would you be into writing a couple?

**Comment by phptek** [comment]
Of course. How unprofessional of me!

**Comment by robbieaverill** [comment]
Not at all! Tests are not necessarily required but would be must appreciated, especially for new features =)

**Comment by phptek** [comment]
Superseded by incoming PRs from @ant1234

**Pull request closed without merging**
