### PR TITLE
FIX: Fixes #65 Use Injector to instantiate created objects. 

### LINKED ISSUE #65: New objects in postHandler() are not created using Injector
In `postHandler()` new objects are not created via `Injector` meaning that developers cannot  make use of dependency injection or any other facet of `Injector` for those objects "managed" by the module.

From:

```
        $obj = new $className();
```

To

```
        use SilverStripe\Core\Injector\Injector;
        ...
        $obj = Injector::inst()->create($className);
```

### PR DESCRIPTION
**Pull request by phptek**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Thanks!

**Comment by phptek** [comment]
@robbieaverill Thanks and without wanting to hassle you (too much) but when will 2.0 be merged into master?

**Comment by robbieaverill** [comment]
@phptek done :)

**Comment by phptek** [comment]
Thanks!!!

**Pull request merged**
