### PR TITLE
SS4: Catch ValidationExceptions and return ValidationResult messages.

### PR DESCRIPTION
**Pull request by chrispenny**
Catch `ValidationExceptions` so that they can be formatted and returned to sender.

Added test.
Added some doc blocks while I was looking around.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Seems like a good change!

**Comment by chrispenny** [comment]
I'm not too sure what to do about the failing unit test?
https://travis-ci.org/silverstripe/silverstripe-restfulserver/builds/347956700?utm_source=github_status&utm_medium=notification
https://travis-ci.org/silverstripe/silverstripe-restfulserver/jobs/347956701

The tests appear to be passing, but then:
`The command "if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi" exited with 1.`

Only for the PHP 5.6 test.

**Comment by robbieaverill** [comment]
@chrispenny it's just a line length issue: https://travis-ci.org/silverstripe/silverstripe-restfulserver/jobs/347956701#L633

**Comment by chrispenny** [comment]
Doh! Thank you, @robbieaverill. Should be golden now.

**Comment by chrispenny** [comment]
@robbieaverill do you think it's worthwhile implementing a similar response format for other `Exception`s, and potentially even for the "success" messages?

I would be happy to work on that today, as I'm still kinda poking around in that space.

**Comment by chrispenny** [comment]
Sorry - not for the "success" message - as that's good atm, but perhaps for the `permissionFailure`/`notFound`/etc messages.

**Comment by robbieaverill** [comment]
If you're asking whether I think that any exceptions thrown during a restful request on the server should be caught, formatted and returned "nicely" to the client, then yes ;D

**Comment by chrispenny** [comment]
Sweet! Thanks. I will work on the generic `Exception` catching today.

**Pull request merged**
